apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
  namespace: oficina
spec:
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
    spec:
      containers:
        - name: oficina-api
          image: ghcr.io/guilherme-fumagali/oficina-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: oficina-api-config
            - secretRef:
                name: oficina-api-secret
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
